version: "3"

services:
  app:
    build:
      context: ./
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: "tail -f /dev/null"
