# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.0
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: |
            sudo apt-get update
            sudo apt-get install -y php-zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Composer vendors
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Run PHPUnit
          command: XDEBUG_MODE=coverage ~/app/vendor/bin/phpunit --coverage-clover ~/app/coverage/coverage.xml --log-junit ~/app/coverage/junit.xml
      - store_test_results:
          path: ~/app/coverage
      - store_artifacts:
          path: ~/app/coverage

      - run:
          name: Run Codecov
          command: bash <(curl -s https://codecov.io/bash)
